version: '2.2'
services:
  esnode:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    container_name: esnode
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - node.name=esnode
      - discovery.seed_hosts=esnode
      - cluster.initial_master_nodes=esnode
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_security:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.1
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://esnode:9200
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  es_security:
    driver: local

networks:
  esnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"